@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Internship *--up> "1" UniqueInterviewDateAndTimeSet
Internship *--right> "1" UniqueRequirementSet
Internship *-left> "1" UniqueApplicationSet

UniqueApplicationSet -left-> Application

Application -up-> "*" InterviewDateAndTime
Application -up-> "*" Requirement

UniqueInterviewDateAndTimeSet --left-> "*" InterviewDateAndTime
UniqueRequirementSet --right-> "*" Requirement

Application *--> "1" Company
Application *--> "1" Position
Application *--> "1" Deadline
Application *--> "1" Priority
Application *--> "1" Completion
Application *--> "1" Status

@enduml
