@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Internship *--up> "1" UniqueInterviewDateAndTimeList
Internship *--right> "1" UniqueRequirementList
Internship *-left> "1" UniqueApplicationList

UniqueApplicationList -left-> Application

Application -up-> "*" InterviewDateAndTime
Application -up-> "*" Requirement

UniqueInterviewDateAndTimeList *-left-> "*" InterviewDateAndTime
UniqueRequirementList *-right-> "*" Requirement

Application *--> Company
Application *--> Position
Application *--> Deadline
Application *--> Priority
Application *--> Completion
Application *--> Status

@enduml
