@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Internship *-right-> "1" UniqueApplicationList

UniqueApplicationList -right-> Application

Application *-up-> "1" RequirementList
Application *-up-> "*" InterviewDateAndTime

RequirementList -right-> "*" Requirement

Application *--> Company
Application *--> Position
Application *--> Deadline
Application *--> Priority
Application *--> Completion
Application *--> Status

@enduml
