@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyInternship <<Interface>>
Interface ReadOnlyUserPrefs <<Interface>>
Interface Model <<Interface>>
Class Internship
Class ReadOnlyInternship
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs


Class UniqueApplicationList
Class Application
Class Company
Class Position
Class Deadline
Class Priority
Class Completion
Class Status
Class RequirementSet
Class InterviewDateAndTimeSet
Class Requirement
Class InterviewDateAndTime
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

Internship .up.|> ReadOnlyInternship

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyInternship
ModelManager -left-> "1" Internship
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

Internship *--> "1" UniqueApplicationList
UniqueApplicationList --> "~* all" Application
Application *--> "1" Company
Application *--> "1" Position
Application *--> "1" Deadline
Application *--> "1" Priority
Application *--> "1" Completion
Application *--> "1" Status
Application *-left> "1" RequirementSet
Application *-right> "1" InterviewDateAndTimeSet
RequirementSet --left> "*" Requirement
InterviewDateAndTimeSet --right> "*" InterviewDateAndTime

ModelManager -->"~* filtered" Application
@enduml
