@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":InternshipParser" as InternshipParser LOGIC_COLOR
participant ":SortCommandParser" as SortCommandParser LOGIC_COLOR
participant "s:SortCommand" as SortCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "model:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("sort pr/")
activate LogicManager

LogicManager -> InternshipParser : parseCommand("sort pr/")
activate InternshipParser

create SortCommandParser
InternshipParser -> SortCommandParser
activate SortCommandParser

SortCommandParser --> InternshipParser
deactivate SortCommandParser

InternshipParser -> SortCommandParser : parse(" pr/")
activate SortCommandParser

create SortCommand
SortCommandParser -> SortCommand
activate SortCommand

SortCommand --> SortCommandParser : s
deactivate SortCommand

SortCommandParser --> InternshipParser : s
deactivate SortCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
SortCommandParser -[hidden]-> InternshipParser
destroy SortCommandParser

InternshipParser --> LogicManager : s
deactivate InternshipParser

LogicManager -> SortCommand : execute(model)
activate SortCommand

SortCommand -> Model : setInternship(sortedInternship)
activate Model

Model --> SortCommand
deactivate Model

create CommandResult
SortCommand -> CommandResult
activate CommandResult

CommandResult --> SortCommand
deactivate CommandResult

SortCommand --> LogicManager : result
deactivate SortCommand

[<--LogicManager
deactivate LogicManager
@enduml
