@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage{

package "UserPrefs Storage" #F4F6F6{
Interface UserPrefsStorage <<Interface>>
Class JsonUserPrefsStorage
}

Interface Storage <<Interface>>
Class StorageManager

package "Internship Storage" #F4F6F6{
Interface InternshipStorage <<Interface>>
Class JsonInternshipStorage
Class JsonSerializableInternship
Class JsonAdaptedInternship
Class JsonAdaptedRequirement
Class JsonAdaptedInterviewDateAndTime
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" InternshipStorage

Storage -left-|> UserPrefsStorage
Storage -right-|> InternshipStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonInternshipStorage .up.|> InternshipStorage
JsonInternshipStorage ..> JsonSerializableInternship
JsonSerializableInternship --> "*" JsonAdaptedInternship
JsonAdaptedInternship -> "*" JsonAdaptedRequirement
JsonAdaptedInternship --> "*" JsonAdaptedInterviewDateAndTime
@enduml
