@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":InternshipParser" as InternshipParser LOGIC_COLOR
participant "u:UndoCommand" as UndoCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "model:Model" as Model MODEL_COLOR
participant ":VersionedInternship" as VersionedInternship MODEL_COLOR
end box
[-> LogicManager : execute("undo")
activate LogicManager

LogicManager -> InternshipParser : parseCommand("undo")
activate InternshipParser

create UndoCommand
InternshipParser -> UndoCommand
activate UndoCommand

UndoCommand --> InternshipParser : u
deactivate UndoCommand

InternshipParser --> LogicManager : u
deactivate InternshipParser

LogicManager -> UndoCommand : execute(model)
activate UndoCommand

UndoCommand -> Model : undoInternship()
activate Model

Model -> VersionedInternship : undo()
activate VersionedInternship

VersionedInternship -> VersionedInternship :setInternship(ReadOnlyInternship)
VersionedInternship --> Model :
deactivate VersionedInternship

Model --> UndoCommand
deactivate Model

UndoCommand --> LogicManager : result
deactivate UndoCommand
UndoCommand -[hidden]-> LogicManager : result
destroy UndoCommand

[<--LogicManager
deactivate LogicManager
@enduml
